# Generated by Django 5.0.3 on 2024-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_alter_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ManyToManyField(to='conf.author'),
        ),
    ]
