# Generated by Django 5.0.3 on 2024-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0010_alter_task_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(),
        ),
    ]
